### ISSUE TITLE
Using universe with swarm

### ISSUE THREAD

**Issue by rmpestano** [arquillian/arquillian-universe-bom#45]
Hi there,

I'm trying to use arquillian universe in [swarm-jsf example](https://github.com/wildfly-swarm/wildfly-swarm-examples/tree/master/jsf/jsf-war) but as soon I add the universe bom I got this exception when I try to run (mvn wildfly-swarm:run):

```
2016-01-24 11:29:04,614 INFO  [org.jboss.as] (Controller Boot Thread) WFLYSRV0025: WildFly Core 2.0.5.Final "Kenny" started in 1434ms - Started 78 of 87 services (18 services are lazy, passive or on-demand)
2016-01-24 11:29:04,665 ERROR [stderr] (main) Exception in thread "main" java.lang.BootstrapMethodError: java.lang.NoClassDefFoundError: org/jboss/shrinkwrap/descriptor/api/jbossdeployment12/JBossDeploymentStructureDescriptor
2016-01-24 11:29:04,667 ERROR [stderr] (main)   at org.wildfly.swarm.container.JBossDeploymentStructureAsset.<init>(JBossDeploymentStructureAsset.java:38)
2016-01-24 11:29:04,667 ERROR [stderr] (main)   at org.wildfly.swarm.container.JBossDeploymentStructureContainer.addModule(JBossDeploymentStructureContainer.java:46)
2016-01-24 11:29:04,668 ERROR [stderr] (main)   at org.wildfly.swarm.undertow.DefaultWarDeploymentFactory.archiveFromCurrentApp(DefaultWarDeploymentFactory.java:57)
2016-01-24 11:29:04,669 ERROR [stderr] (main)   at org.wildfly.swarm.undertow.DefaultWarDeploymentFactory.create(DefaultWarDeploymentFactory.java:50)
2016-01-24 11:29:04,669 ERROR [stderr] (main)   at org.wildfly.swarm.container.Container.createDefaultDeployment(Container.java:503)
2016-01-24 11:29:04,670 ERROR [stderr] (main)   at org.wildfly.swarm.container.Container.deploy(Container.java:390)
2016-01-24 11:29:04,671 ERROR [stderr] (main)   at org.wildfly.swarm.Swarm.simpleMain(Swarm.java:63)
2016-01-24 11:29:04,671 ERROR [stderr] (main)   at org.wildfly.swarm.Swarm.main(Swarm.java:55)
2016-01-24 11:29:04,672 ERROR [stderr] (main) Caused by: java.lang.NoClassDefFoundError: org/jboss/shrinkwrap/descriptor/api/jbossdeployment12/JBossDeploymentStructureDescriptor
2016-01-24 11:29:04,673 ERROR [stderr] (main)   ... 8 more
2016-01-24 11:29:04,674 ERROR [stderr] (main) Caused by: java.lang.ClassNotFoundException: org.jboss.shrinkwrap.descriptor.api.jbossdeployment12.JBossDeploymentStructureDescriptor
2016-01-24 11:29:04,674 ERROR [stderr] (main)   at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
2016-01-24 11:29:04,675 ERROR [stderr] (main)   at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
```

dependency tree can be [found here](http://pastebin.com/g0RKrVPY). Should I exclude swarm shrinkwrap dependencies in order to use universe? thanks in adavance!

**Comment by aslakknutsen** [comment]
Could you try using locally build universe-bom? The master branch has Core 1.1.0 which rely on Descriptors Alpha8.. Which Swarm might need..
